import type { Metadata } from "next";
import "./globals.css";
import Header from "@/ui/header";

import { Noto_Sans, Open_Sans } from "next/font/google";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const notoSans = Noto_Sans({
	subsets: ["latin"],
	weight: ["100", "400", "600", "700"], // thin, regular, semibold, bold
	variable: "--font-noto-sans",
});

const openSans = Open_Sans({
	subsets: ["latin"],
	weight: ["400", "600", "700"], // regular, semibold, bold
	variable: "--font-open-sans",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${notoSans.variable} ${openSans.variable} relative font-open-sans max-w-[1920px] mx-auto`}
			>
				<Header
					className={`w-[1030px] mx-auto relative z-2
								2xl:w-full `}
				></Header>
				{children}
			</body>
		</html>
	);
}

/*
	px-[50px] py-[16px] 3xl:px-[100px]
*/
