import type { Metadata } from "next";
import "./globals.css";
import Header from "@/ui/header";
import { Noto_Sans, Open_Sans, Inter } from "next/font/google";
import ConditionalFooter from "@/ui/conditionalFooter";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const notoSans = Noto_Sans({
	subsets: ["latin"],
	weight: ["100", "400", "600", "700"],
	variable: "--font-noto-sans",
});

const openSans = Open_Sans({
	subsets: ["latin"],
	weight: ["400", "600", "700"],
	variable: "--font-open-sans",
});

const inter = Inter({
	subsets: ["latin"],
	weight: ["100", "400", "600", "700"],
	variable: "--font-inter",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${notoSans.variable} ${openSans.variable} ${inter.variable}
							flex flex-col
							font-open-sans max-w-[1030px] min-h-[100vh] mx-auto px-page
							2xl:max-w-[1920px] relative`}
			>
				<Header className={`w-full mx-auto relative z-2`} />
				<main className="mb-[50px] grow-1 flex flex-col items-center">
					{children}
				</main>
				<ConditionalFooter />
			</body>
		</html>
	);
}
